### ISSUE TITLE
Einthusan Error on Kodi Krypton

### ISSUE THREAD

**Issue by bkgit9** [eintamil/eintamil.github.io#1]
Getting Einthusan error.Einthusan not working on Krypton.Cant upgrade Kodi in setup box ,so is there any way to make it work on Kodi 17

**Comment by eintamil** [comment]
Which version of Einthusan add-on did you try? Will you be able to try Einthusan2.x and paste the error message from kodi.log here? Can you be more specific on the version 17.x? You can find it in settings.

**Comment by eintamil** [comment]
Tested "Einthusan Video Addon - Version 2.x" on Kodi 17.6 and works fine. Hence closing this issue. If any further concerns, open a new issue at https://github.com/eintamil/repository.eintamil/issues
