### ISSUE TITLE
Addon Settings

### ISSUE THREAD

**Issue by srikanthku** [eintamil/eintamil.github.io#2]
Can you enable Addon Settings to pass username and password

**Comment by eintamil** [comment]
Which version of Kodi and Einthusan add-on are you using? 
I have to be honest here, unfortunately I do not have a premium account to test this scenario. 
I will try to find some solution for this.

**Comment by srikanthku** [comment]
18.6 and eintamil version 2 (python 2.x)

**Comment by eintamil** [comment]
Thanks for the information. Try using the below beta version and confirm if this works as expected - will then merge it into master.

https://github.com/eintamil/repository.eintamil/raw/user-login-settings/zips/plugin.video.einthusan2/plugin.video.einthusan2-2.0.2.zip

**Comment by srikanthku** [comment]
Sorry, I don’t have a way to test unless it is pushed to master

**Comment by eintamil** [comment]
Ok, it is now available in master. Please refresh/check for updates and upgrade to 2.0.2

**Comment by srikanthku** [comment]
I was able to enter the credentials and play an uhd video, I think it’s working. Thank you
